// <auto-generated />
using System;
using HangfireOrchestratorComponent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HangfireOrchestratorComponent.Migrations
{
    [DbContext(typeof(PocDbContext))]
    partial class PocDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HangfireOrchestratorComponent.Data.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Task1JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Task2JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Task3JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Task4JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Task5JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });
#pragma warning restore 612, 618
        }
    }
}
